### ISSUE TITLE
ClassNotFoundException on version 2.10.1

### ISSUE THREAD

**Issue by wburgers** [xmlunit/xmlunit#296]
We're using xmlunit-legacy in our organization.
Since today/yesterday I'm getting an error when running `mvn install` on my project.

When I revert back to 2.10.0, everything works again.
So that's what I did.

Let me know how if there's anything I can do to help.

Error (I removed the name of the test class and package as that should not be relevant):
```
java.lang.NoClassDefFoundError: org.xmlunit.diff.ComparisonListener
	at org.custommonkey.xmlunit.Diff.getDifferenceEngine(Diff.java:461)
	at org.custommonkey.xmlunit.Diff.compare(Diff.java:267)
	at org.custommonkey.xmlunit.Diff.similar(Diff.java:279)
	at org.custommonkey.xmlunit.XMLAssert.assertXMLEqual(XMLAssert.java:131)
	at org.custommonkey.xmlunit.XMLAssert.assertXMLEqual(XMLAssert.java:236)
	at org.custommonkey.xmlunit.XMLAssert.assertXMLEqual(XMLAssert.java:186)
	at org.custommonkey.xmlunit.XMLTestCase.assertXMLEqual(XMLTestCase.java:213)
	at nl.blaat.TestClass(ServiceTest.java:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.ClassNotFoundException: org.xmlunit.diff.ComparisonListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:827)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1101)
	... 35 more
```

**Comment by bodewig** [comment]
Are you using OSGi? I've updated the bundle plugin and as I don't use OSGi myself - and none of our tests do - it is quite possible Ive broken something there.

**Comment by cortlepp** [comment]
FYI: We have the same problem over at [axis](https://github.com/apache/axis-axis2-java-core/pull/920).

I haven't gotten the chance yet, but I'll look into whether this was related to the bundle plugin test.

**Comment by bodewig** [comment]
Thank you @cortlepp , the tests of the legacy module all pass, so it seems to be finding the class just fine when run inside the Maven reactor build. Any help in figuring out the cause is much appreciated.

**Comment by bodewig** [comment]
OK, I can reproduce this completely without OSGi. For some reason the transitive dependency from xmlunit-legacy to xmlunit-core is no longer resolved in 2.10.1, so it must be something I have changed to the POMs, I just don't see what.

**Comment by bodewig** [comment]
OK, https://repo1.maven.org/maven2/org/xmlunit/xmlunit-legacy/2.10.1/xmlunit-legacy-2.10.1.pom is different from https://github.com/xmlunit/xmlunit/blob/main/xmlunit-legacy/pom.xml . Next suspect is the shade plugin I use for the "sumo" artifact.

**Comment by bodewig** [comment]
I believe #297 fixes the problem. I've just published new 2.10.2-SNAPSHOT artificats and the uploaded POM looks fine.

Could anybody of you please locally [add the snapshot repo](https://github.com/xmlunit/xmlunit?tab=readme-ov-file#snapshot-builds) and give 2.10.2-SNAPSHOT a try just to confirm it no just works on my machine?

**Comment by wburgers** [comment]
Sorry for the late reply. I've been busy at work with other stuff.

Even if I add the repository for snapshots into the project where it went wrong, I still can't resolve 2.10.2-SNAPSHOT for some reason.
So I'm not able to test it yet.
Will get back when I know more.

**Comment by bodewig** [comment]
thanks @cortlepp  and @wburgers , I will push out a new release later today.

**Comment by wburgers** [comment]
Works flawlessly.
Thank you!

**Comment by bodewig** [comment]
you're welcome
